servlet/jsp_mvc/src/tr/obss/jss2014/bean/NameBean.java
package tr.obss.jss2014.bean;

import java.util.Random;

import javax.ejb.Stateless;
import javax.inject.Named;

/**
 * Session Bean implementation class MyBean
 */
@Stateless
@Named
public class NameBean {

	private Random random = new Random();
	
	/**
	 * Default constructor.
	 */
	public NameBean() {
		// TODO Auto-generated constructor stub
	}

	public String getRandomName() {
		return names[random.nextInt(names.length)];
	}

	private static String[] names = { "Sharlene Dean", "Charles Moody",
			"Allie Dotson", "Mendoza Mccarty", "Autumn Luna", "Parker Osborn",
			"Gail Carr", "Franks Davis", "Guthrie Wise", "Oneil Cox",
			"Hensley Sims", "Gladys Sanford", "Elsie Newton", "Gay Collins",
			"Rosemarie Townsend", "Burke Bernard", "Nona Crawford",
			"Whitney Carrillo", "Myra Jefferson", "Maricela Roy", "Liza Blair",
			"Alexandra Ruiz", "Winnie Mays", "Rowe Franklin", "Heidi Grimes",
			"Althea Mckenzie", "Fulton Head", "Haley Carroll", "Ryan Conley",
			"Arnold Golden", "Lynette Campos", "Pena Contreras", "Bean Wong",
			"Francis Ballard", "Case Dillon", "Madden Mayo", "Rodgers Hyde",
			"Marina Price", "Lola Stewart", "Griffith Boyd", "Diaz Day",
			"Lloyd Briggs", "Gonzalez Moss", "Mcclain Spears", "Corine Nelson",
			"Cohen Hutchinson", "Saunders Mullins", "Robyn Mcgee",
			"Rose Mcpherson", "Ida Aguirre", "Wood Talley", "Deana Livingston",
			"Audrey Mcfadden", "Huffman Crane", "Mitzi Coffey",
			"Gretchen English", "Anna Bishop", "Horn Padilla",
			"Bianca Castillo", "Massey Howell", "Conner Michael",
			"Alta Hudson", "Danielle Dominguez", "Black Fleming",
			"Benjamin Robles", "Emerson Wright", "Jewel Owens",
			"Virginia Workman", "Humphrey Rhodes", "Rene Rich",
			"Cheri Salazar", "Hull Love", "Sheree Abbott", "Barnett Mack",
			"Albert Dennis", "Blanche Serrano", "Wade Cherry", "Lisa Pope",
			"Joyce Sykes", "Sosa Reilly", "Reva Vincent", "Hunter Eaton",
			"Kitty Cole", "Elsa Ramos", "Eddie Salinas", "Castillo Ellison",
			"Browning Cantrell", "Benson Mercer", "Garcia Maddox",
			"Beth Garcia", "Stacey Carey", "Sweet Noble", "Vicky Baird",
			"Lenora Buckley", "Walton Britt", "Guerrero Macias", "Wise Sparks",
			"Dennis Harrell", "Strickland Bryan", "Earlene Buchanan" };

}

servlet/jsp_mvc/src/tr/obss/jss2014/servlet/DispatcherServlet.java
package tr.obss.jss2014.servlet;

import java.io.IOException;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 * Servlet implementation class DispatcherServlet
 */
@WebServlet("/example")
public class DispatcherServlet extends HttpServlet {

	private static final String BUTTON_DATE = "buttonDate";
	private static final String START_DATE = "start_date";
	private static final long serialVersionUID = 1L;
       

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		
		if("true".equals(request.getParameter("button"))){
			session.setAttribute(BUTTON_DATE, new Date());
			response.sendRedirect(request.getContextPath()+request.getServletPath());
			return;
		}
		
		if(session.getAttribute(START_DATE)==null){
			session.setAttribute(START_DATE, new Date());
		}
		
		Object sessionStartDate = session.getAttribute(START_DATE);
		
		Object buttonTime = session.getAttribute(BUTTON_DATE);
		String buttonTimeString = buttonTime==null?"Never":buttonTime.toString();
		request.setAttribute("currentTime", new Date());
		request.setAttribute("sessionTime", sessionStartDate);
		request.setAttribute("buttonTime", buttonTimeString);
		request.getRequestDispatcher("/WEB-INF/page1.jsp").forward(request, response);
	}

}

servlet/jsp_mvc/WebContent/WEB-INF/page1.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link rel="stylesheet" href="./css/bootstrap.min.css">
<link rel="stylesheet" href="./css/jumbotron-narrow.css">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>JSP MVC Example</title>
</head>
<body>
<div class="container">
      <div class="header">
        <h3 class="text-muted">JSP MVC Example</h3>
      </div>

      <div class="jumbotron">
        <h1>JSP MVC Example</h1>
        <p class="lead">The button below keeps track of the last time it was pressed!</p>

        <p><a class="btn btn-lg btn-success" href="?button=true" role="button">Click Me!</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Current Time</h4>
          <p>${ currentTime }</p>

          <h4>Last Button Click Time</h4>
          <p>${ buttonTime }</p>

          <h4>Session Start Time</h4>
          <p>${ sessionTime }</p>
          
          <h4>Random Name</h4>
          <p>${ nameBean.randomName }</p>
        </div>
      </div>

      <div class="footer">
        <p>&copy; OBSS 2014</p>
      </div>

    </div> <!-- /container -->
</body>
</html>