jpa/blog/src/tr/com/obss/jss2014/blog/model/UserDetail.java
package tr.com.obss.jss2014.blog.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class UserDetail extends BaseModel {

	@Column(nullable=false)
	private String firstName;
	@Column(nullable=false)
	private String lastName;
	private String bio;
	@Temporal(TemporalType.DATE)
	private Date dateOfBirth;

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getBio() {
		return bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	
	public String getFullName(){
		return firstName+" "+lastName;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("UserDetail [firstName=").append(firstName)
				.append(", lastName=").append(lastName).append(", bio=")
				.append(bio).append(", dateOfBirth=").append(dateOfBirth)
				.append(", id=").append(id).append(", version=")
				.append(version).append(", createDate=").append(createDate)
				.append(", updateDate=").append(updateDate).append("]");
		return builder.toString();
	}

}

jpa/blog/src/tr/com/obss/jss2014/blog/servlet/HomeServlet.java
package tr.com.obss.jss2014.blog.servlet;

import java.io.IOException;
import java.util.List;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import tr.com.obss.jss2014.blog.dao.BlogPostDao;
import tr.com.obss.jss2014.blog.model.BlogPost;

/**
 * Servlet implementation class HomeServlet
 */
@WebServlet("/home")
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
	@Inject
	private BlogPostDao blogPostDao;

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		List<BlogPost> latestBlogPosts = blogPostDao.getLatestBlogPosts(10);
		if(!latestBlogPosts.isEmpty()){
			request.setAttribute("recentPosts", latestBlogPosts);
			request.setAttribute("latestPost", latestBlogPosts.get(0));
		}
		request.getRequestDispatcher("/WEB-INF/view/home.jsp").forward(request, response);
	}


}

jpa/blog/src/tr/com/obss/jss2014/blog/servlet/LoginServlet.java
package tr.com.obss.jss2014.blog.servlet;

import java.io.IOException;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import tr.com.obss.jss2014.blog.dao.UserDao;
import tr.com.obss.jss2014.blog.model.User;

/**
 * Servlet implementation class LoginServlet
 */
@WebServlet(urlPatterns={"/login", "/logout"})
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	@Inject
	private UserDao userDao;

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		if(request.getServletPath().equals("/logout")){
			session.invalidate();
			response.sendRedirect("/blog/login");
			return;
		}
		if(session.getAttribute("user")!=null){
			response.sendRedirect("/blog/home");
			return;
		}
		if(session.getAttribute("login_failed")!=null){
			request.setAttribute("loginFailed", true);
			session.removeAttribute("login_failed");
		}
		request.getRequestDispatcher("/WEB-INF/view/login.jsp").forward(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String username = request.getParameter("username");
		String password = request.getParameter("password");
		User user = userDao.findByUsernameAndPassword(username, password);
		HttpSession session = request.getSession();
		if(user!=null){
			session.setAttribute("user", user);
			response.sendRedirect("/blog/home");
		}else{
			session.setAttribute("login_failed", true);
			response.sendRedirect("/blog/login");
		}
	}

}

jpa/blog/WebContent/WEB-INF/view/addComment.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
  <h1>Add Comment</h1>
  <form action="./addComment" method="POST">
    <label for="title_input">Title (optional)</label>
    <input type="text" name="title" id="title_input">
    <br>
    <label for="email_input"></label>
    <input type="text" name="email" id="email_input">
    <br>
    <label for="comment_input"></label>
    <textarea name="comment" id="comment_input" cols="30" rows="10"></textarea>
    <br>
    <input type="hidden" name="postId" value="${ postId }">
    <c:if test="${ not empty parentId }">
	    <input type="hidden" name="parentId" value="${ parentId }">
    </c:if>
    <button type="submit">Add comment</button>
  </form>

</body>
</html>

jpa/blog/WebContent/WEB-INF/view/addPost.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
  <h1>Add new blog post</h1>
  <div>
    <form action="./addPost" method='POST'>
      <label for="title_input">Post Title:</label>
      <input type="text" name="title" id="title_input">
      <br>
      <label for="content_input">Content:</label>
      <textarea name="content" id="content_input" cols="30" rows="10"></textarea>
      <br>
      <button type="submit">Add Blog Post</button>
    </form>
  </div>
</body>
</html>

jpa/blog/WebContent/WEB-INF/view/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
  <h1>JSP MVC DAO JPA EJB BLOG</h1>
  <c:if test="${ not empty latestPost}">
    <div class="latest-post">
      <h2>${ latestPost.title }</h2>
      <h3>a post by ${ latestPost.author.detail.fullName }</h3>
      <p>${ latestPost.content }</p>
    </div>
  </c:if>
  <c:if test="${ not empty recentPosts }">
    <h3>Recent Posts</h3>
    <ul>
      <c:forEach items="${ recentPosts }" var="post">
        <li>
          <a href="./post?id=${ post.id }">${ post.title }</a>
        </li>
      </c:forEach>
    </ul>
  </c:if>

</body>
</html>

jpa/blog/WebContent/WEB-INF/view/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Blog - Login</title>
</head>
<body>
<c:if test="${ not empty loginFailed }">
	<div class="error">
		Login failed. Check your credentials and try again.
	</div>
</c:if>
  <div>
    <form action="./login" method="POST">
      <label for="username_input">Username:</label>
      <input type="text" name="username" id="username_input">
      <br>
      <label for="password_input">Password:</label>
      <input type="password" name="password" id="password_input">
      <br>
      <button type="submit">Login</button>
    </form>
  </div>
</body>
</html>

jpa/blog/WebContent/WEB-INF/view/postDetail.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@taglib prefix="custom" tagdir="/WEB-INF/tags" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Blog - ${ post.title } </title>
</head>
<body>
  <h1>${ post.title }</h1>
  <h2>Date: ${ post.createDate }</h2>
  <h2>A post by ${ post.author.detail.fullName }</h2>
  <p>${ post.content }</p>
  <hr />
  <a href="./addComment?postId=${ post.id }">Add comment</a>
  <h3>Comments</h3>
  <c:forEach items="${ post.comments }" var="comment">
	<custom:comment comment="${ comment }" post="${ post }"/>
	<hr />
  </c:forEach>

</body>
</html>